### PR TITLE
Prod Rebrand Devskrate TO TechMobie

### LINKED ISSUE #37: scrolling panel in dashboard
test 1

### PR DESCRIPTION
**Pull request by VasaviLagishetty**
Looks like many files but simple changes

**Theme Color**

image

**Search Changes**

image

**Post page Changes**

image

**Tags Page Changes**

image

**Footer Changes**

image

**Author/Contributor Changes**

image

### CODE REVIEW

**Comment by puneethkanna** [comment]
Everything is good. Can we make Mobie into our default color in the navigation bar.

**Comment by puneethkanna** [comment]
> Everything is good. Can we make Mobie into our default color in the navigation bar.

Tech in 1 color and Mobie in 1 color

**Review by SriSatyaLokesh — APPROVED** [review]
✔✔✔

**Comment by puneethkanna** [comment]
If it takes time, we can push directly and can make the changes later.

**Pull request merged**
